services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend-service
    volumes:
      - backend_data:/data
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "3000:3000"  
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge
    internal: false  # false чтобы фронтенд мог выходить наружу